<script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
<script src="<?php echo SERVERURL; ?>vistas/js/sweetalert2.min.js"></script>
<script src="<?php echo SERVERURL; ?>vistas/js/speakingurl.js"></script>
<script src="<?php echo SERVERURL; ?>vistas/js/jquery.stringtoslug.min.js"></script>
<script src="<?php echo SERVERURL; ?>vistas/js/chosen.jquery.min.js"></script>
<script src="<?php echo SERVERURL; ?>vistas/js/jscolor.js"></script>
<script src="<?php echo SERVERURL; ?>vistas/js/main.js"></script>